### ISSUE TITLE
03

### ISSUE THREAD

**Issue by Rabah-A** [niccokunzmann/memory.quelltext.eu#16]

**Comment by niccokunzmann** [comment]
Hallo @Rabah-A you created an Issue. Now, we can discuss things.

DE: Sprichst Du Deutsch? Du kannst auch hier antworten,

**Comment by Rabah-A** [comment]
Hallo Nicco,
Ja ich habe eine erstellt,wie können auch hier diskutieren
Fehlt mir aber zeit alles das zu verstehen und auch ein schups von jemandem ,es hilft auch :)

**Comment by Rabah-A** [comment]
zu zeit ich versuche den Information zu verstehen
https://rogerdudler.github.io/git-guide/index.de.html#comment-2126505194
ob das helft
und auch ich bin dran die befehle zu lernen
https://book.git-scm.com/docs/git/de

**Comment by niccokunzmann** [comment]
Hi, ja, das ist nützlich, die zu lernen. Ich habe einen kleinen Guide erstellt, der vielleicht nicht 100% richtig ist. https://github.com/niccokunzmann/memory.quelltext.eu#development

**Comment by niccokunzmann** [comment]
Wenn Du Hilfe brauchst, einfach Bescheid sagen.

**Comment by Rabah-A** [comment]
Das ist wirklich nett von dir, ja ich brauche helfe und ich habe viel fragen,Z.b: wie man kan ein Programm existierren lassen auf dem Plattform,kannst du mal bitte ein Video schicken.

Téléchargez Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by niccokunzmann** [comment]
Das Memory-Spiel ist eine Webseite. Die kann man runterladen und im Browser ansehen. Wenn man git clone macht, lädt er alle Versionen herunter. Man kann dann die index.html-Datei öffnen z.B. mit Firefox oder Chrome.

**Comment by niccokunzmann** [comment]
Hallo,

ich mache die Issue mal zu und wir machen eine neue auf, wenn wir was bereden.
