### ISSUE TITLE
Black dots are better visible

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/memory.quelltext.eu#17]
The brown dots are barely visible on the paper sheets. Please make them black.

**Comment by tauqeerali1** [comment]
Hey, I want to work on this issue

**Comment by niccokunzmann** [comment]
@tauqeerali1, this issue is already fixed, see the pull request #20. It is also mentioned above. I forgot to close it. Sorry! If you like to work on something else in this repository, just let me know. I am closing this now to avoid confusion. Feel free to write something here if you see it fit!
